/* Generated by scripts/build-tokens.mjs from tokens/yalatus.tokens.json. Do not edit. */

export const COLOR_KEYS = ["bg-canvas","bg-inverse","surface-accent-subtle","surface-subtle","surface-default","surface-strong","surface-inverse","surface-disabled","surface-readonly","surface-danger","surface-success","surface-warning","surface-info","fg-accent","fg-support","fg-default","fg-subtle","fg-inverse","fg-disabled","fg-readonly","fg-danger","fg-success","fg-warning","fg-info","fg-placeholder","fg-link","fg-link-hover","fg-link-visited","on-accent","on-danger","on-success","on-warning","on-info","on-inverse","action-accent","action-hover","action-active","action-disabled","border-accent","border-subtle","border-default","border-strong","border-inverse","border-disabled","border-readonly","focus-ring","focus-offset"] as const;
export const SPACE_KEYS = ["space-4","space-8","space-12","space-16","space-24","space-32","space-40","space-48","space-64","space-80","space-96","space-104","space-112","space-120","space-144","space-192","space-256"] as const;
export const RADIUS_KEYS = ["radius-2","radius-4","radius-20"] as const;
export const TEXT_KEYS = ["display","title","heading-1","heading-2","heading-3","heading-4","heading-5","prose","body-lg","body","label-uppercase","label","caption","numeral-lg","numeral","value","code"] as const;

export type ColorKey = (typeof COLOR_KEYS)[number];
export type SpaceKey = (typeof SPACE_KEYS)[number];
export type RadiusKey = (typeof RADIUS_KEYS)[number];
export type TextKey = (typeof TEXT_KEYS)[number];
