/** build-icons — writes src/components/Icon/Icon.names.ts from the SVG files in src/assets/icons. Exits 1 when the folder is missing. Env: none. */
import { readdir, writeFile } from 'node:fs/promises';

const ROOT = new URL('../', import.meta.url);
const ICONS = new URL('src/assets/icons/', ROOT);
const TARGET = new URL('src/components/Icon/Icon.names.ts', ROOT);

const files = (await readdir(ICONS)).filter(file => file.endsWith('.svg')).sort();
const names = files.map(file => file.replace(/\.svg$/, ''));

const source = [
  '/* Generated by scripts/build-icons.mjs from src/assets/icons. Do not edit. */',
  '',
  `export const ICON_NAMES = ${JSON.stringify(names)} as const;`,
  '',
  'export type IconName = (typeof ICON_NAMES)[number];',
  '',
].join('\n');

await writeFile(TARGET, source);
console.log(`Icon.names.ts written (${names.length} icons)`);
